export const topStars = [
    {
      index: 0,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '19.69%',
        left: '94.94%',
        opacity: 0.359761,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 1,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '88.61%',
        left: '73.99%',
        opacity: 0.304633,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 2,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '0.64%',
        left: '82.77%',
        opacity: 0.398113,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 3,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '23.54%',
        left: '18.64%',
        opacity: 0.183229,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 4,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '34.67%',
        left: '42.14%',
        opacity: 0.105835,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 5,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '75.15%',
        left: '25.19%',
        opacity: 0.295171,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 6,
      initialState: 'medium',
      style: {
        '--transition-duration': '250ms',
        top: '79.31%',
        left: '83.94%',
        opacity: 0.352466,
        width: '1px',
        height: '1px',
        transform: 'scale(2)',
      },
    },
    {
      index: 7,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '37.02%',
        left: '61.92%',
        opacity: 0.374873,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 8,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '81.54%',
        left: '9.22%',
        opacity: 0.223346,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 9,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '69.82%',
        left: '70.34%',
        opacity: 0.134485,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 10,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '3.97%',
        left: '1.53%',
        opacity: 0.356208,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 11,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '72.08%',
        left: '91.98%',
        opacity: 0.162145,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 12,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '47.92%',
        left: '75.76%',
        opacity: 0.332941,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 13,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '54.35%',
        left: '12.15%',
        opacity: 0.162237,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 14,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '46.32%',
        left: '8.84%',
        opacity: 0.190937,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 15,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '86.48%',
        left: '7.03%',
        opacity: 0.264327,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 16,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '45.56%',
        left: '74.01%',
        opacity: 0.335825,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 17,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '6.24%',
        left: '63.51%',
        opacity: 0.138889,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 18,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '76.79%',
        left: '64.94%',
        opacity: 0.395712,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 19,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '55.7%',
        left: '78.44%',
        opacity: 0.300363,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 20,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '4.93%',
        left: '28.22%',
        opacity: 0.389917,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 21,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '77.36%',
        left: '93.94%',
        opacity: 0.325167,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 22,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '36.45%',
        left: '30.14%',
        opacity: 0.27765,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 23,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '96.1%',
        left: '30.66%',
        opacity: 0.300609,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 24,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '26.27%',
        left: '20.32%',
        opacity: 0.361239,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 25,
      initialState: 'medium',
      style: {
        '--transition-duration': '250ms',
        top: '88.04%',
        left: '24.75%',
        opacity: 0.378752,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 26,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '11.21%',
        left: '11.18%',
        opacity: 0.169384,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 27,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '6.77%',
        left: '17.07%',
        opacity: 0.191704,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 28,
      initialState: 'high',
      style: {
        '--transition-duration': '250ms',
        top: '0.98%',
        left: '39.31%',
        opacity: 0.284362,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 29,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '84.89%',
        left: '43.58%',
        opacity: 0.126566,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 30,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '38.12%',
        left: '9.76%',
        opacity: 0.211491,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 31,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '42.56%',
        left: '54.09%',
        opacity: 0.152863,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 32,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '7.91%',
        left: '86.44%',
        opacity: 0.399046,
        width: '1px',
        height: '1px',
      },
    },
  ]
  
  export const rightStars = [
    {
      index: 0,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '30.01%',
        left: '99.16%',
        opacity: 0.127221,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 1,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '43.6%',
        left: '85.14%',
        opacity: 0.113115,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 2,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '7.64%',
        left: '83.77%',
        opacity: 0.203447,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 3,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '69.77%',
        left: '8.88%',
        opacity: 0.239298,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 4,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '6.26%',
        left: '32.37%',
        opacity: 0.22582,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 5,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '20.01%',
        left: '17.13%',
        opacity: 0.132696,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 6,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '32.03%',
        left: '73.44%',
        opacity: 0.229473,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 7,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '23.93%',
        left: '6.19%',
        opacity: 0.312444,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 8,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '56.92%',
        left: '44.85%',
        opacity: 0.27169,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 9,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '84.34%',
        left: '78.7%',
        opacity: 0.338621,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 10,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '4.69%',
        left: '43.94%',
        opacity: 0.398852,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 11,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '3.94%',
        left: '10.62%',
        opacity: 0.3661,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 12,
      initialState: 'medium',
      style: {
        '--transition-duration': '250ms',
        top: '31.32%',
        left: '58.77%',
        opacity: 0.232452,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 13,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '50.32%',
        left: '24.24%',
        opacity: 0.394243,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 14,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '30.68%',
        left: '39.72%',
        opacity: 0.234098,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 15,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '40.43%',
        left: '95.64%',
        opacity: 0.200183,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 16,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '40.95%',
        left: '65.72%',
        opacity: 0.338265,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 17,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '26.31%',
        left: '86.52%',
        opacity: 0.276154,
        width: '1px',
        height: '1px',
      },
    },
  ]
  
  export const bottomStars = [
    {
      index: 0,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '76.7%',
        left: '46.64%',
        opacity: 0.366004,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 1,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '62.3%',
        left: '96.08%',
        opacity: 0.123576,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 2,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '10.31%',
        left: '17.67%',
        opacity: 0.280304,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 3,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '31.77%',
        left: '56.33%',
        opacity: 0.36646,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 4,
      initialState: 'high',
      style: {
        '--transition-duration': '250ms',
        top: '68.35%',
        left: '17.8%',
        opacity: 0.155083,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 5,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '95.53%',
        left: '17.47%',
        opacity: 0.345442,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 6,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '53%',
        left: '73.67%',
        opacity: 0.15354,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 7,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '8.42%',
        left: '59.16%',
        opacity: 0.254704,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 8,
      initialState: 'high',
      style: {
        '--transition-duration': '250ms',
        top: '66.39%',
        left: '80.9%',
        opacity: 0.227822,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 9,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '15.83%',
        left: '30.46%',
        opacity: 0.273594,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 10,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '14.19%',
        left: '14.44%',
        opacity: 0.192297,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 11,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '27.04%',
        left: '19.83%',
        opacity: 0.289619,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 12,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '44.8%',
        left: '93.76%',
        opacity: 0.282142,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 13,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '60.87%',
        left: '66.34%',
        opacity: 0.327325,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 14,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '93.04%',
        left: '18.6%',
        opacity: 0.330227,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 15,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '73.5%',
        left: '68.93%',
        opacity: 0.134291,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 16,
      initialState: 'medium',
      style: {
        '--transition-duration': '250ms',
        top: '44.61%',
        left: '34.17%',
        opacity: 0.293858,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 17,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '84.12%',
        left: '7.07%',
        opacity: 0.173581,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 18,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '73.46%',
        left: '66.99%',
        opacity: 0.287107,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 19,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '21.21%',
        left: '26.82%',
        opacity: 0.10309,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 20,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '47.04%',
        left: '72.36%',
        opacity: 0.157351,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 21,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '70.19%',
        left: '51.83%',
        opacity: 0.219852,
        width: '1px',
        height: '1px',
      },
    },
  ]
  
  export const leftStars = [
    {
      index: 0,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '15.63%',
        left: '36.52%',
        opacity: 0.280548,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 1,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '22.09%',
        left: '62.52%',
        opacity: 0.366737,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 2,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '57.36%',
        left: '70.38%',
        opacity: 0.277537,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 3,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '31.65%',
        left: '87.95%',
        opacity: 0.130971,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 4,
      initialState: 'high',
      style: {
        '--transition-duration': '250ms',
        top: '12.86%',
        left: '0.93%',
        opacity: 0.305343,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 5,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '62.82%',
        left: '5.8%',
        opacity: 0.154447,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 6,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '21.7%',
        left: '63.24%',
        opacity: 0.171123,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 7,
      initialState: 'medium',
      style: {
        '--transition-duration': '250ms',
        top: '83.9%',
        left: '4.82%',
        opacity: 0.378177,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 8,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '30.24%',
        left: '29.1%',
        opacity: 0.177397,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 9,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '71.07%',
        left: '16.27%',
        opacity: 0.216409,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 10,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '82.12%',
        left: '8.97%',
        opacity: 0.369943,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 11,
      initialState: 'high',
      style: {
        '--transition-duration': '250ms',
        top: '21.23%',
        left: '62.25%',
        opacity: 0.21265,
        width: '1px',
        height: '1px',
        transform: 'scale(1)',
      },
    },
    {
      index: 12,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '21.74%',
        left: '60.79%',
        opacity: 0.226666,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 13,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '70.68%',
        left: '23.84%',
        opacity: 0.32512,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 14,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '20.04%',
        left: '62.22%',
        opacity: 0.282333,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 15,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '7.05%',
        left: '88.87%',
        opacity: 0.370539,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 16,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '53.45%',
        left: '27.54%',
        opacity: 0.331918,
        width: '1px',
        height: '1px',
      },
    },
    {
      index: 17,
      initialState: 'off',
      style: {
        '--transition-duration': '250ms',
        top: '7.39%',
        left: '49.28%',
        opacity: 0.392967,
        width: '1px',
        height: '1px',
      },
    },
  ]